### ISSUE TITLE
update supermarket.chef.io please

### ISSUE THREAD

**Issue by jcii** [CBarraford/diamond_cookbook#17]
Hello,

Would you be willing to update the supermarket with your latest release? Are you blocked from doing so?

Thanks

-Jimmy

**Comment by CBarraford** [comment]
i have no idea how to do so. i feel like the site is confusing to use, is it just me?

**Comment by jcii** [comment]
I am willing to help with that! We have an enterprise supermarket. The instructions there say this: 

* Ensure you have a Chef repo configured with your private key
* Share your cookbook with knife cookbook site share COOKBOOK_NAME CATEGORY (options)

The instructions on our supermarket also refer to https://docs.chef.io/knife_cookbook_site.html#share, which says: 
```
This action will require a user account and a certificate for https://supermarket.chef.io. By default, knife will use the user name and API key that is identified in the configuration file used during the upload; otherwise these values must be specified on the command line or in an alternate configuration file.
```

So, I think you need a key in your ~/.chef/knife.rb associated with an account on Supermarket. Then you upload from knife. What happens when you do `knife cookbook site share diamond "Applications"` ?

**Comment by CBarraford** [comment]
I'm no longer using this cookbook personally (work at a different company than i did when i wrote the cookbook), so i don't have the cookbook in my `knife` at all.

I can add you as a collaborator if you give me your supermarket username.

**Comment by jcii** [comment]
ok. jcii. I just enabled it for public supermarket.

**Comment by CBarraford** [comment]
Cool, just added you as a collaborator to the supermarket.

**Comment by drenalin23** [comment]
I just recently used stove to update the kibana cookbook in the supermarket and it was very easy.  If you haven't check it out I would recommend setting it up...
https://supermarket.chef.io/tools/stove

**Comment by drenalin23** [comment]
btw - Thanks @CBarraford for the work to get this cookbook where it is and to @jcii for looking to update at the supermarket - was just looking at the supermarket today to see if we can deprecate a very old one off diamond cookbook.

**Comment by CBarraford** [comment]
I've just updated the supermarket with version 2.0.5 of the cookbook. Thanks @drenalin23!
